metric: COCO
num_classes: 3

TrainDataset:
  name: COCODataSet
  image_dir: images_train
  anno_path: annotations/instance_train.json_coco.json
  dataset_dir: E:\data\0111_testdata\data_labeled\slice_coco2560
  data_fields: ['image', 'gt_bbox', 'gt_class', 'is_crowd']

EvalDataset:
  name: COCODataSet
  image_dir: images_val
  anno_path: annotations/instance_val.json_coco.json
  dataset_dir: E:\data\0111_testdata\data_labeled\slice_coco2560

TestDataset:
  name: ImageFolder
  anno_path: annotations/instance_train.json_coco.json # also support txt (like VOC's label_list.txt)
  dataset_dir: E:\data\0111_testdata\data_labeled\slice_coco2560
